### ISSUE TITLE
What does mean question marks(?) at the beginning of two lines? twilio_api_v2010.yaml

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#12]
### Issue Summary
https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_api_v2010.yaml
There are question marks at the beginning of these two lines -
line 1472
line 13284
There is also colon ( : ) at the beginning of the next line.
It's a bug or feature?

```
      type: object
    ? api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on.incoming_phone_number_assigned_add_on_extension
    : properties:
        account_sid:
```

```
     x-path-type: list
  ? /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{AssignedAddOnSid}/Extensions/{Sid}.json
  : description: 'TODO: Resource-level docs'
    get:
      description: Fetch an instance of an Extension for the Assigned Add-on.
      parameters:
```

**Comment by thinkingserious** [comment]
Hello @balucha,

Those are key (?) / value (:) indicators. I believe our generator is adding those in the case of exceptionally long strings.

With best regards,

Elmer

**Comment by balucha** [comment]
No, its not in my generator. It is in your API spec.
Open twilio_api_v2010.yaml (https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_api_v2010.yaml) and check
lines 1472 and 13287. You will see the key ? at the beginning of this lines.
Looks like it has something to do with TODO description on the line 13288. No other endpoint has TODO in description.

**Comment by shwetha-manvinkurke** [comment]
Hi @balucha yes, he meant it's probably in _our_ generator. The question is there any problem you are facing because of this?

**Comment by balucha** [comment]
No, it doesn't cause us any problems. We filter those characters out.

**Comment by JenniferMah** [comment]
If the character's are not filtered out do you receive any errors for those additional characters?
