### ISSUE TITLE
Do you plan to add an operationId field to your API?

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#15]
**operationId** field would help us.

We are trying to automatically generate the application from your API, but now we have a problem with how to name each operation. Automatically generated names based on current information from API specifications don't look good, so we need to update them manually.

This also would ensure the same operation names in different applications based on your API. Because everyone will be able to use your suggested operation names.

http://spec.openapis.org/oas/v3.0.1#operation-object

**Comment by JenniferMah** [comment]
Hi @balucha
We do plan on adding the `operationId` field. I will link the corresponding PR when it is public.

**Comment by JenniferMah** [comment]
@balucha
You can track  the progress on the addition of the `operationId` field in [this PR](https://github.com/twilio/twilio-oai/pull/16).
