### ISSUE TITLE
What date formats can we use in the DateSent parameter?

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#21]
There is a "YYYY-MM-DD" format(with '2009-07-06' example) in the description, but various date formats are listed on the website in the examples. I've tested various formats and they all work(2020-12-12T10:53:43-08:00, 2020-12-12T10:53:43Z, 2020-12-12T10:53:43.000-0800, 2020, 2020-12).
So what date formats can we use in the DateSent parameter?

```
- description: 'The date of the messages to show. Specify a date as `YYYY-MM-DD`
          in GMT to read only messages sent on this date. For example: `2009-07-06`.
          You can also specify an inequality, such as `DateSent<=YYYY-MM-DD`, to read
          messages sent on or before midnight on a date, and `DateSent>=YYYY-MM-DD`
          to read messages sent on or after midnight on a date.'
```

**Comment by JenniferMah** [comment]
Hi @balucha
Please use the date format listed in the description which is `YYYY-MM-DD`.

**Comment by balucha** [comment]
What if I only want to receive new messages(calls,...) since the last query?
In case of a query with this date(```YYYY-MM-DD```), I will receive duplicate messages. I will receive the message that I have already received before.
I want to receive only new messages and I can't achieve it with this date format. 
Check the documentation link(listed below ) for ```Read: List messages matching filter criteria```. There is different format.

[Twilio documentation](https://www.twilio.com/docs/sms/api/message-resource?code-sample=code-read-list-messages-matching-filter-criteria&code-language=twilio-cli&code-sdk-version=1.x)

**Comment by JenniferMah** [comment]
If you wanted to only receive new messages since the last query date you would need to save the last query date and use it as a parameter when listing data. You should be able to use the DateSent> parameter, which reads as date sent after YYYY-MM-DD, with your last query date to get any new messages.
