### ISSUE TITLE
Don't plan to add a parameter to sort the results?

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#22]
In the actual state we can't change sorting direction and the list result is sorted from the newest to the oldest.

We have several scenarios where it is better for us to sort from the oldest.

**Comment by JenniferMah** [comment]
Hi @balucha
What request are you making that needs sorting direction options?

**Comment by balucha** [comment]
List call, List message, List Call recording, List Recording and maybe some others where it's interesting to know which data is the oldest.
For these data, it would be useful for us to be able to change the order.

**Comment by JenniferMah** [comment]
Hi @balucha we don't currently have a parameter to sort the results. This parameter would need to be implemented internally before it could be utilized within the open api spec. As a current work around I would suggest storing that data in reverse order when receiving data from the twilio api.
