### ISSUE TITLE
Github actions failing when issues are raised

### ISSUE THREAD

**Issue by savage-alex** [twilio/twilio-oai#34]
When I raised an issue, I had an email from Github that it started and failed an action

![image](https://user-images.githubusercontent.com/25430683/115297295-f5047680-a153-11eb-8275-920673f2823d.png)

Here is the run: https://github.com/twilio/twilio-oai/actions/runs/764828871
![image](https://user-images.githubusercontent.com/25430683/115297252-e7e78780-a153-11eb-9516-6358a0ee8594.png)

**Comment by shwetha-manvinkurke** [comment]
Hi @savage-alex Thank you for reporting the issue! 

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by JenniferMah** [comment]
This bug has been fixed and the github action is now building successfully.
