### ISSUE TITLE
AvailablePhoneNumbers API missing

### ISSUE THREAD

**Issue by andygarfield** [twilio/twilio-oai#41]
Any plans to create the AvailablePhoneNumbers API spec on here?

e.g.
```
https://api.twilio.com/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Local.json
```

**Comment by childish-sambino** [comment]
https://github.com/twilio/twilio-oai/blob/aed0152455f6d3c7ce3b7869c86499132dfd72a7/spec/yaml/twilio_api_v2010.yaml#L8942

**Comment by andygarfield** [comment]
Ah thanks. Github search is broken.
