### ISSUE TITLE
Field media_external_location in composition object is missing

### ISSUE THREAD

**Issue by jlpedrosa** [twilio/twilio-oai#48]
### Issue Summary
Field `media_external_location` is part of the object `v1/Compositions`. It is not documented, but present and required when using S3 as a storage media. 

### Steps to Reproduce
Schema issues, no need steps to reproduce. 

### Code Snippet
```json
{
    "status": "completed",
    "trim": false,
    "video_layout": {},
    "date_completed": "2021-11-15T12:23:27Z",
    "format": "mp4",
    "url": "https://video.twilio.com/v1/Compositions/CJXxxxxxxxxx",
    "bitrate": 107,
    "media_external_location": "https://buckets3.amazonaws.com/compositions/CJXxxxxxxxxx.mp4",
    "date_deleted": null,
    "account_sid": "ACYYYYYY",
    "duration": 11,
    "audio_sources": [
        "*"
    ],
    "sid": "CJxxxxxx",
    "room_sid": "RMyyyyyy",
    "date_created": "2021-11-15T12:20:21Z",
    "size": 144106,
    "resolution": "640x480",
    "audio_sources_excluded": [],
    "links": {
        "media": "https://video.twilio.com/v1/Compositions/CJ2XXXXXXX/Media"
    }
}
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-oai version: 
* open version:

**Comment by twilio-dx** [comment]
Ahoy! Thank you for opening your first issue here! If this request is regarding troubleshooting your application, please reach out to the support team via [https://support.twilio.com](https://support.twilio.com).

**Comment by shwetha-manvinkurke** [comment]
Where in the docs do you see that field should be present? It's a private field that shouldn't be exposed yet.

**Comment by eshanholtz** [comment]
Closing due to lack of customer response.
