### ISSUE TITLE
Unable to export the Open API Specification to Azure APIM

### ISSUE THREAD

**Issue by restlessankyyy** [twilio/twilio-oai#49]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1.  Sign up for Azure Portal
2. Create an APIM instance
3. Navigate to API and select create API
4. Select Open API specification API
5. Enter the GitHub URL `https://github.com/twilio/twilio-oai/blob/main/spec/json/twilio_ip_messaging_v2.json`
6. See the error.

### Screenshot
![Screenshot 2021-11-24 at 19 35 03](https://user-images.githubusercontent.com/23651587/143295669-ca630eaf-3658-4efd-b902-45e11385c3b1.png)

### Technical details:
* twilio-oai version: 
* open version:

**Comment by twilio-dx** [comment]
Ahoy! Thank you for opening your first issue here! If this request is regarding troubleshooting your application, please reach out to the support team via [https://support.twilio.com](https://support.twilio.com).

**Comment by shwetha-manvinkurke** [comment]
Does it give you any details describing why the spec is invalid according to them?

**Comment by restlessankyyy** [comment]
I am trying to import open API spec. I am easily able to import all my rest apis to azure APIM but this one.

**Comment by shwetha-manvinkurke** [comment]
Have you tried importing any of our other specs besides ip_messaging_v*?

**Comment by JenniferMah** [comment]
Closing due inactivity. Please open a new Github issue if you still need assistance.

**Comment by restlessankyyy** [comment]
@shwetha-manvinkurke I haven't tried. However I was more inclined towards this API to try out.
