### ISSUE TITLE
twilio-oai tag doesn't exist on SO

### ISSUE THREAD

**Issue by hurricane-socrates** [twilio/twilio-oai#55]
Creating such a tag requires at least 1500 whatevers; which I do not have.

My question involves Rust and the OAI if someone on SO would pick it up. I can only ask one question at a time on SO. I have several about the OAI Rust implementation. To be clear, I have it working, so these are questions to see if the Rust implementation needs better documentation or improvements in the generated code.

https://stackoverflow.com/questions/71907349/twilio-openapi-implementation-when-using-more-than-one-api

According to 
https://stackoverflow.com/questions/tagged/twilio-oai+or+twilio+open

the search is for the tag [twilio-oai]. I was trying to get attention on that tag when I came across the inability to add the tag.

**Comment by twilio-dx** [comment]
Ahoy! Thank you for opening your first issue here! If this request is regarding troubleshooting your application, please reach out to the support team via [https://support.twilio.com](https://support.twilio.com).

**Comment by hurricane-socrates** [comment]
Hi! No, it's not troubleshooting. It's about the implementation when there is more than one API involved.

**Comment by hurricane-socrates** [comment]
I'll try elsewhere
