### ISSUE TITLE
TrustHub spec does not include route to BrandRegistrations

### ISSUE THREAD

**Issue by jbellos** [twilio/twilio-oai#60]
### Issue Summary
When making a request to BrandRegistrations, the mock server returns no route found. I believe this route needs to be added to the twilio_trusthub_v1.json / yaml file.

### Steps to Reproduce
1. Start a mock server: prism mock https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_trusthub_v1.json
2. Create a new Twilio Client with accountSid/token as per normal, pointing to the prism host.
3. Make a request to brand registration:
```
const brand = await twilioClient.messaging.brandRegistrations.create({
        brandType: 'STARTER',
        customerProfileBundleSid: starterCustomerProfileSid,
        a2PProfileBundleSid: a2pStarterTrustBundleSid,
});
```
4. Receive error in Prism Server: 
```
prism_1  | [9:15:05 PM] › [HTTP SERVER] post /v1/a2p/BrandRegistrations ✖  error     Request terminated with error: https://stoplight.io/prism/errors#NO_PATH_MATCHED_ERROR: Route not resolved, no path matched
```
5. Search`twilio_trusthub_v1.json` for any keyword of BrandRegistrations: no matches found.

### Code Snippet
See above

### Exception/Log
See above

### Technical details:
* twilio-oai version: twilio_trusthub_v1.json
* open version:

**Comment by twilio-dx** [comment]
Ahoy! Thank you for opening your first issue here! If this request is regarding troubleshooting your application, please reach out to the support team via [https://support.twilio.com](https://support.twilio.com).

**Comment by beebzz** [comment]
Hi @jbellos, thanks for submitting an issue. Since this is a feature request, feel free to open a [support ticket](https://twilio.com/help/contact) in order to properly track this issue.

**Comment by childish-sambino** [comment]
The `brandRegistrations` path and operations are part of the `messaging.twilio.com` subdomain which is contained in a separate API doc: https://github.com/twilio/twilio-oai/blob/551f4406f9fc03ccef0878ccc8920006d659d23d/spec/json/twilio_messaging_v1.json#L2616

**Comment by jbellos** [comment]
Thanks, I see that now. I just wasn't expecting it when the rest of the requests passed through trusthub. 
Appreciate the follow-up!
