### ISSUE TITLE
Response status code formatting does not comply with the OpenAPI 3.0 specification

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#9]
### Issue Summary
Your API does not comply with the OpenAPI 3.0 specification
Response status code formatting does not comply with the OpenAPI 3.0 specification. 
Response code must be enclosed in quotation marks.

Citation from the OpenAPI 3.0 specification 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#patterned-fields-1

"Any HTTP status code can be used as the property name, but only one property per code, to describe the expected response for that HTTP status code. A Reference Object can link to a response that is defined in the OpenAPI Object's components/responses section. This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML."

Part of your API specification with the wrong formatting of the response status code.
```responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.v2010.account'
          description: Created

**Comment by JenniferMah** [comment]
@balucha 
Thanks for pointing this out! This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
